const productData = [
  {
    productId: 1,
    seller: [
      {
        id: 4,
        price: 9.99,
        tax: '0.50',
        shippingFee: 0,
        totalPrice: '10.49',
        returnPolicy: 'Return-eligible for 30 days',
        name: 'Ultricies',
        offer: 'Free delivery by Thu, Oct 29',
      },
      {
        id: 9,
        price: 9.99,
        tax: '0.50',
        shippingFee: 0,
        totalPrice: '10.49',
        returnPolicy: 'Return-eligible for 90 days',
        name: 'Tortor',
        offer: 'Free delivery by Wed, Nov 4',
      },
      {
        id: 3,
        price: 9.99,
        tax: '0.50',
        shippingFee: 5,
        totalPrice: '15.49',
        returnPolicy: 'Return-eligible for 30 days',
        name: 'Consequat',
        offer: 'Spend $35 for free delivery by Fri, Oct 30',
      },
      {
        id: 10,
        price: 19.99,
        tax: '1.00',
        shippingFee: 5,
        totalPrice: '25.99',
        returnPolicy: 'Return-eligible for 60 days',
        name: 'Nisl',
        offer: 'Spend $20 for free delivery by Sat, Oct 31',
      },
      {
        id: 7,
        price: 29.99,
        tax: '1.50',
        shippingFee: 5,
        totalPrice: '36.49',
        returnPolicy: 'Return-eligible for 90 days',
        name: 'Adipiscing Elit Pellentesque',
        offer: 'Spend $35 for free delivery by Fri, Oct 30',
      },
      {
        id: 8,
        price: 29.99,
        tax: '1.50',
        shippingFee: 5,
        totalPrice: '36.49',
        returnPolicy: 'Return-eligible for 30 days',
        name: 'Odio',
        offer: 'Spend $20 for free delivery by Wed, Nov 4',
      },
      {
        id: 5,
        price: 39.99,
        tax: '2.00',
        shippingFee: 3,
        totalPrice: '44.99',
        returnPolicy: 'Return-eligible for 90 days',
        name: 'Fames Nunc',
        offer: 'Spend $35 for free delivery by Sat, Oct 31',
      },
      {
        id: 2,
        price: 49.99,
        tax: '2.50',
        shippingFee: 0,
        totalPrice: '52.49',
        returnPolicy: 'Return-eligible for 30 days',
        name: 'Sit Amet',
        offer: 'Free delivery by Sat, Oct 31',
      },
      {
        id: 1,
        price: 59.99,
        tax: '3.00',
        shippingFee: 3,
        totalPrice: '65.99',
        returnPolicy: 'Return-eligible for 60 days',
        name: 'Vulputate Ut',
        offer: 'Spend $20 for free delivery by Fri, Oct 30',
      },
      {
        id: 6,
        price: 99.99,
        tax: '5.00',
        shippingFee: 0,
        totalPrice: '104.99',
        returnPolicy: 'Return-eligible for 90 days',
        name: 'Morbi',
        offer: 'Free delivery by Sat, Oct 31',
      },
    ],
  },
  {
    productId: 2,
    seller: [
      {
        id: 5,
        price: 9.99,
        tax: '0.50',
        shippingFee: 3,
        totalPrice: '13.49',
        returnPolicy: 'Return-eligible for 90 days',
        name: 'Fames Nunc',
        offer: 'Spend $35 for free delivery by Sat, Oct 31',
      },
      {
        id: 6,
        price: 29.99,
        tax: '1.50',
        shippingFee: 0,
        totalPrice: '31.49',
        returnPolicy: 'Return-eligible for 90 days',
        name: 'Morbi',
        offer: 'Free delivery by Sat, Oct 31',
      },
      {
        id: 1,
        price: 29.99,
        tax: '1.50',
        shippingFee: 3,
        totalPrice: '34.49',
        returnPolicy: 'Return-eligible for 60 days',
        name: 'Vulputate Ut',
        offer: 'Spend $20 for free delivery by Fri, Oct 30',
      },
      {
        id: 3,
        price: 29.99,
        tax: '1.50',
        shippingFee: 5,
        totalPrice: '36.49',
        returnPolicy: 'Return-eligible for 30 days',
        name: 'Consequat',
        offer: 'Spend $35 for free delivery by Fri, Oct 30',
      },
      {
        id: 4,
        price: 39.99,
        tax: '2.00',
        shippingFee: 0,
        totalPrice: '41.99',
        returnPolicy: 'Return-eligible for 30 days',
        name: 'Ultricies',
        offer: 'Free delivery by Thu, Oct 29',
      },
      {
        id: 2,
        price: 49.99,
        tax: '2.50',
        shippingFee: 0,
        totalPrice: '52.49',
        returnPolicy: 'Return-eligible for 30 days',
        name: 'Sit Amet',
        offer: 'Free delivery by Sat, Oct 31',
      },
    ],
  },
];

module.exports = productData;
